### ISSUE TITLE
Class Dutchento\Vatfallback\Console\Command\Validate does not exist

### ISSUE THREAD

**Issue by Rickertje** [Dutchento/m2-vatfallback#8]
Class Dutchento\Vatfallback\Console\Command\Validate does not exist
while installing
on M2 2.2.2
Any ideas on what might be wrong?

**Comment by mkor** [comment]
Hi, having the same issue on Magento 2.2.5 Open Source.

Tried to fix the errors I ran into as they occurred, but still stuck.

in **Model/VatNumber/Config.php**, I replaced DataInterface with Data
```
namespace Dutchento\Vatfallback\Model\VatNumber;

use Dutchento\Vatfallback\Model\VatNumber\Config\Data;

class Config implements ConfigInterface
{
    /** @var Data  */
    private $dataSource;

    /**
     * Config constructor.
     * @param Data $dataSource
     */
    public function __construct(Data $dataSource)
    {
     	$this->dataSource = $dataSource;
    }

    /**
     * @inheritdoc
     */
    public function get(): array
    {
     	return $this->dataSource->get();
    }
}
```

next, in **Model/VatNumber/Config/Reader.php**, there is a bad reference:
`string $domDocumentClass = \Dom::class,`
I removed the backslash and added the following use:
`use Magento\Framework\Config\Dom;`

Next, we then run into an error on the include:
```
[20-Dec-2018 10:11:22 UTC] PHP Fatal error:  Uncaught Error: Call to a member function getNamedItem() on null in <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php:51
Stack trace:
#0 <M2_DIR>/vendor/magento/framework/Config/Reader/Filesystem.php(171): Dutchento\Vatfallback\Model\VatNumber\Config\Converter->convert(Object(DOMDocument))
#1 <M2_DIR>/vendor/magento/framework/Config/Reader/Filesystem.php(130): Magento\Framework\Config\Reader\Filesystem->_readFiles(Object(Magento\Framework\Config\FileIterator))
#2 <M2_DIR>/vendor/magento/framework/Config/Data.php(104): Magento\Framework\Config\Reader\Filesystem->read()
#3 <M2_DIR>/vendor/magento/framework/Config/Data.php(92): Magento\Framework\Config\Data->initData()
#4 <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Data.php in <M2_DIR>/vendor/dutchento/m2-vatfallback/Model/VatNumber/Config/Converter.php on line 51
```

**Comment by sandermangel** [comment]
Hi Rickertje, would you have any more details?

**Comment by JeroenBoersma** [comment]
this is an old issue, tried it, couldn't be reproduced, so my guess is that it is already resolved.
tested against `~2.3.1`

**Comment by peterjaap** [comment]
Closing until further notice
